# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Joseph McGuire | Personal Blog
email: joseph.c.mcg@gmail.com
description: Personal blog and portfolio with retro design
baseurl: "" # This should be an empty string for yourusername.github.io
url: "https://joseph-c-mcguire.github.io" # The base URL for your site
github_username: joseph-c-mcg
google_analytics: "{{ site.secrets.GOOGLE_ANALYTICS }}"

# Exclude these files and directories from the site build
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _site/

remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-katex
  - jekyll-paginate

mailchimp:
  api_key: "{{ site.secrets.MAILCHIMP_API_KEY }}"
  list_id: "{{ site.secrets.MAILCHIMP_LIST_ID }}"

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

fixed_navbar: top

# Collections for different content types
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  services:
    output: true
    permalink: /services/:path/

# Pagination
paginate: 6
paginate_path: "/blog/page:num/"