services:
  - type: web
    name: joseph-c-mcguire-frontend
    runtime: docker
    rootDir: frontend
    dockerfilePath: Dockerfile
    envVars:
      - key: PUBLIC_SITE_URL
        fromService:
          type: web
          name: joseph-c-mcguire-frontend
          property: url
      - key: PUBLIC_BACKEND_URL
        fromService:
          type: web
          name: joseph-c-mcguire-backend
          property: url

  - type: web
    name: joseph-c-mcguire-backend
    runtime: docker
    rootDir: backend
    dockerfilePath: Dockerfile
    envVars:
      - key: FRONTEND_URL
        fromService:
          type: web
          name: joseph-c-mcguire-frontend
          property: url
